env:
  global:
  - NO_SIMPLECOV=true
  - secure: Ys71anAIjNI1caD4vzbe8rchDxW01pYq7VPd+BNZl7L3XSeNh6BOKoB61Mxul2uxe+cmuOtgu2kWJaG8Q/2dc2Uk1WIlwPtDLI0RGkaXi1nxcA38wBzE/x5nWqnuO2IC8sH7dnJoCGJh6l3Wh1fa6atM+AumE+opMVmpjzv1XEE=
  - secure: RRszwiF6zjaFdt9ChebyyxJhya4PVepnCVYn8AgBHsvpYtItn4y/1W5hyRvCAaqg+Fw7OXzjS+bDb0amln8PwEX7dbB8OIX0srRXlEmqZsxvp1aZO4QJE8mBU1SGeDz975/riEqM+WrUs0I3P+YoS0rzYAfDdrgOsZuMOXMv3RQ=
  - secure: UvtPU/JRExEq0ZR5XclUxIsDw0TdYY2RXRRkrwghBm1od4OasFzv9lPnG3OSCxO9rTG/dxs7P2bzsCA9Z1wcvFvhudcp/uTAHhRh/Bs0iebpRzjXno51dvs86RfXdSuN2gsDhd8mehji8hqmlhwpSznujEekp3Vvtuca40aA/Tk=
  matrix:
  - FOG_REAL=false
  - FOG_REAL=true
matrix:
  exclude:
  - rvm: 1.9.2
    env: FOG_REAL=true
  - rvm: 1.9.3
    env: FOG_REAL=true
  - rvm: jruby-19mode
    env: FOG_REAL=true
branches:
  only:
  - master
language: ruby
cache: bundler
rvm:
- 2.1.1
- 1.9.3
script: bundle exec rake test --trace
