env:
  global:
  - NO_SIMPLECOV=true
  - secure: U48+AvJmsfRtyPPi5CIqc3WuUOlPPJVlw3zBSmwFoVdLAOZ25teb0GycLO2pwgAHaOPfVaEbmY/LXvSruSEa2AGxy2lNFkN4LIqyxeP7sfyTEtkI948VK7Y8v3Fa6KUSrStFSkIRYRzihOEypQIX3Cw46ZF08KRBFDTMl4qlfQs=
  - secure: B1H57jUYG6IS26Dn4Kgs7MYpyxIfRvAwyxoTG0KS7H/3aRiw1NOWRDwMVnAPg1OgwxG1NsZTfmTCA7zXggYYFmrpSPbFJULWoFA2LuRkIVow0/IoRmmLnO9jzfXxnn8Gl876wp7jyhmMdRwVbWAqsuzO7K0ruGrguwnmHq/1/no=
  - secure: mliRgueCZpl66Cgo/LSNmJYLRLEhL4/EmY2Nk1g8SgnrZApdIzEJ3VxHLz0bOenbYSrWRBhmoWgth7O8ak6iBm2l/i1WYzI0ZikCQ+HaOy9qLM81lNkqmdgp/mgV3hJWAPl0Phh3bFWKT/rhzJg1ko3qoOMtOVcl9b1+FGu6whQ=
  matrix:
  - FOG_REAL=false
  - FOG_REAL=true
matrix:
  exclude:
  - rvm: 1.9.2
    env: FOG_REAL=true
  - rvm: 1.9.3
    env: FOG_REAL=true
  - rvm: jruby-19mode
    env: FOG_REAL=true
branches:
  only:
  - master
language: ruby
cache: bundler
rvm:
- 2.1.1
- 1.9.2
- 1.9.3
- jruby-19mode
script: bundle exec rake test --trace
